#!name=Kurge
#!desc=我的 surge 的自定义配置，包含 http-api、DoH 的配置。
#hahaha
[General]
doh-server = https://dns.alidns.com/dns-query?
http-api = zou970514@0.0.0.0:6166
[Rule]
PROCESS-NAME,/Applications/Spark.app/Contents/MacOS/Spark,🔰国外流量 // Spark
DOMAIN-SUFFIX,hockeyapp.net,🔰国外流量 // Spark
DOMAIN-SUFFIX,firebaseio.com,🔰国外流量 // Spark
DOMAIN,usage.readdle.com,🔰国外流量 // Spark
DOMAIN,api.amplitude.com,🔰国外流量 // Spark
DOMAIN,app.smartmailcloud.com,🔰国外流量 // Spark
